### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by Rahaf-96** [GSG-K3/pizza-shop#2]
### -Description: 
Website for pizza shop, it can be used by the customers to order pizza or employees to check the orders.

### -User Journey: 
As a customer I should be able to order a specific type of pizza by filling a form.
As an employee I should be able to check all orders details.

### -File Structure: 
```
- public
   - css
        - index.css
        - customer.css
        - employee.css
   - js
       - index.js
       - customer.js
       - employee.js
   - index.html
   - customer.html
   - employee.html

- server
  - controllers
   - database
       - db_build.js
       - db_build.sql
       - db_connection.js
   - app.js

- test
   - test.js
```
### -Schema:
![Untitled Diagram (1)](https://user-images.githubusercontent.com/54964739/75233563-b5493580-57c1-11ea-85c4-f128a13c9005.png)

### -Team
Banan, Duha, Hanan, Rahaf

**Comment by hshahwan** [comment]
@Rahaf-96  the type of value for extra cheese will be boolean?

**Comment by Rahaf-96** [comment]
yes, extra cheese, mushrooms and peppironi will be boolean. we will present them as checkboxes in the form.
