### ISSUE TITLE
Heroku link is not working!

### ISSUE THREAD

**Issue by sara219** [GSG-K3/pizza-shop#24]
When I click on the link in the readme, Heroku _doesn't_ work.
I think you use GitHub pages for it, which is wrong, **you should deploy your project on Heroku and use Heroku DB**...

**Comment by Duha96** [comment]
thanks for your attention , we will do it :+1: @sara219

**Comment by hshahwan** [comment]
@Duha96 could you add the link in the readme, the link that you added not working too
